apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Values.deploy.name}}"
spec:
  selector:
    matchLabels:
      app: jabbr
  template:
    metadata:
      labels:
        app: jabbr
    spec:
      containers:
        - image: "{{.Values.deploy.acr}}:{{.Values.deploy.imageTag}}"
          imagePullPolicy: Always
          name: jabbr
          resources:
          env:
            - name: CONNSTR_Jabbr
              value: "Server=tcp:{{.Values.deploy.dbServer}},1433;Initial Catalog={{.Values.deploy.dbName}};Persist Security Info=False;User ID={{.Values.deploy.dbUser}};Password={{.Values.deploy.dbPasswd}};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
          ports:
          - containerPort: {{.Values.deploy.containerPort}}
            protocol: TCP
      nodeSelector:
        "beta.kubernetes.io/os": windows            
      restartPolicy: Always        
