apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Values.deploy.name}}"
spec:
  selector:
    matchLabels:
      app: jabbr
  template:
    metadata:
      labels:
        app: jabbr
    spec:
      containers:
        - image: "griffwinacr.azurecr.io/jabbr:{{.Values.deploy.imageTag}}"
          imagePullPolicy: Always
          name: jabbr
          resources:
          env:
            - name: CONNSTR_Jabbr
              value: {{.Values.deploy.connectionString}}
          ports:
          - containerPort: {{.Values.deploy.containerPort}}
            protocol: TCP
      nodeSelector:
        "beta.kubernetes.io/os": windows            
      restartPolicy: Always        